# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # ✅ Keep Python package dependencies up to date
  - package-ecosystem: "pip"
    directory: "."  # location of requirements.txt or pyproject.toml
    schedule:
      interval: "monthly"  # or "daily", "weekly", "yearly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "pip"
    ignore:
      - dependency-name: "tensorflow"
        versions: ["<2.0.0"]  # optional if you want to avoid breaking updates

  # ✅ Keep GitHub Actions dependencies up to date
  - package-ecosystem: "github-actions"
    directory: "."  # root for GitHub workflows
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
  # ✅ Keep Dockerfile dependencies up to date
  - package-ecosystem: "docker"
    directory: "."  # location of Dockerfile
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"