name: merrypopins
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.23
  - pandas>=2.2
  - scipy>=1.10
  - scikit-learn>=1.2
  - matplotlib>=3.7
  - pip
  - pip:
      - tensorflow>=2.10
      - merrypopins
