site_name: Indenter
site_url: https://serprateai.github.io/indenter/
repo_url: https://github.com/SerpRateAI/indenter
repo_name: GitHub

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - API:
      - load_datasets: reference/indenter.load_datasets.md
      - preprocess: reference/indenter.preprocess.md
      - locate: reference/indenter.locate.md
      - statistics: reference/indenter.statistics.md
      - make_dataset: reference/indenter.make_dataset.md
  - Contributing: contributing.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
      options:
        rendering:
          show_root_toc_entry: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true