# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Merrypopins CI Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      # 1) Check out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Set up the Python interpreter(s)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3) Cache pip dependencies for speed
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # also install pytest if not in requirements
          pip install pytest

      
      # 5) Run pre-commit hooks
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
      
      # 5) Run tests with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=merrypopins --cov-report=xml

      # Upload coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          # if your repo is public you don’t need a token,
          # otherwise add a CODECOV_TOKEN secret in your repo settings
          # token: ${{ secrets.CODECOV_TOKEN }}
